name: rcapp
description: A new Flutter application.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  carousel_slider: ^2.2.1
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  table_calendar: ^2.2.1
  firebase_helpers: ^0.1.8
  google_maps_flutter: ^0.5.30
  geolocator: ^5.3.2+2
  flutter_spinkit: ^4.1.2
  flushbar: ^1.10.4
  http: ^0.12.2
  flutter_full_pdf_viewer: ^1.0.6
  image_picker: ^0.6.7+7
  firebase_storage: ^3.0.7
  focused_menu: ^1.0.1
  file_picker: ^1.13.3
  permission_handler: ^5.0.1+1
  flutter_downloader: ^1.5.0
  path_provider: ^1.6.14
  dropdown_formfield: ^0.1.2
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
